spring.config.import=optional:secrets.properties

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.dddhegzsmwbsdoqmmmqt
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.from=${MAIL_FROM:${MAIL_USERNAME}}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SMTP_SSL_ENABLE:false}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:${MAIL_HOST}}
spring.mail.properties.mail.smtp.ssl.checkserveridentity=${MAIL_SSL_CHECK_SERVER_IDENTITY:false}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT:20000}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT:20000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT:20000}